#!/bin/bash -x
#SBATCH --account=jinm60
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --output=ntrain=2000-gpu=1-out.%j
#SBATCH --error=ntrain=2000-gpu=1-err.%j
#SBATCH --time=12:00:00
#SBATCH --partition=dc-gpu
#SBATCH --gres=gpu:1

cd /p/home/jusers/dick3/jureca/fourier_neural_operator/
module load GCCcore/9.3.0
module load PyTorch
module load h5py
module load scikit
python 2d_time_wrapper.py --ntrain=2000
sacct -j $SLURM_JOBID -l -P

